name-template: 'v$RESOLVED_VERSION 🌈'

tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: 🚀 Features and Enhancements
    label: feature
  - title: 🧰 Maintenance
    label: maintenance
  - title: 🔥 Technical Improvements
    label: toi
  - title: ✨ Dependency Upgrades
    label: dependencies

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch

template: |
  ## What’s Changed

  $CHANGES