name: Release Preview Package
on:
  push:
    branches:
      - main
## Testt

env:
  ## Sets environment variable
  PACKAGE_NAME: ${{ github.event.repository.name }}

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-preview-package:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: update_release_draft
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set VERSION env
        run: echo "VERSION=${{needs.update_release_draft.outputs.tag_name}}-preview.$(date +'%Y.%m.%d.%H.%M.%S')" >> $GITHUB_ENV

      - name: dump env
        run: echo "$VERSION"
