name: Release Preview Package
on:
  push:
    branches:
      - main
## Testt

env:
  ## Sets environment variable
  PACKAGE_NAME: ${{ github.event.repository.name }}

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - id: release-drafter        
        uses: release-drafter/release-drafter@v5  
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set VERSION env
        run: echo "VERSION=${steps.release-drafter.outputs.tag_name:1}-beta${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

      - name: dump VERSION env
        run: echo $VERSION

  release-preview-package:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: update_release_draft
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: dump env
        run: echo "$VERSION"
